## Preparing the Data

Wrangling the data & exploring the data

In [92]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

red_wine = pd.read_csv('winequality-red.csv', sep=';')
red_wine.info()
red_wine.head()
red_wine.tail()
red_wine.describe()
red_wine.isnull().sum()
red_wine.duplicated().sum()
red_wine = red_wine.drop_duplicates()
red_wine.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

(1359, 12)

In [93]:
white_wine = pd.read_csv('winequality-white.csv', sep=';')

white_wine.info()
white_wine.head()
white_wine.tail()
white_wine.describe()
white_wine.isnull().sum()
white_wine.duplicated().sum()
white_wine = white_wine.drop_duplicates()
white_wine.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

(3961, 12)

In [94]:
# Add wine type label
red['wine_type'] = 'red'
white['wine_type'] = 'white'

# Combine datasets
wine = pd.concat([red, white], ignore_index=True)

# Drop duplicates
wine = wine.drop_duplicates()

In [95]:
wine.describe(include='O')

       wine_type
count       5320
unique         2
top        white
freq        3961

In [96]:
dfw = wine.copy()

## Encoding Categorical Variables

In [97]:
# Binary encoding for wine type (nominal)

dfw['wine_type'].replace({'red': 0, 'white': 1}, inplace=True)

# view first 5 rows
dfw.head()

/var/folders/4z/5y7_7y714mg469xjsc3rqc5r0000gn/T/ipykernel_96104/3586842656.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfw['wine_type'].replace({'red': 0, 'white': 1}, inplace=True)
/var/folders/4z/5y7_7y714mg469xjsc3rqc5r0000gn/T/ipykernel_96104/3586842656.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dfw['wine_type'].replace({'red': 0, 'white': 1}, inplace=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,wine_type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,0

## Split the data

In [104]:
# X = features (all columns except wine_type)
# y = target (wine_type)
X = dfw.drop(columns=['wine_type'])
y = dfw['wine_type']

In [105]:
from sklearn.model_selection import train_test_split

# 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [106]:
y_test.shape

(1064,)

In [107]:
X_test.shape

(1064, 12)

## Building the model

In [127]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [128]:
from sklearn.linear_model import LogisticRegression

# max_iter increased to 500 to avoid convergence warnings
LR_model = LogisticRegression(random_state=42, max_iter=500)
LR_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=500, random_state=42)

In [132]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = LR_model.predict(X_test_scaled)

# Accuracy score
print("Accuracy:", accuracy_score(y_test, y_pred))

# Classification report
print(classification_report(y_test, y_pred))

Accuracy: 0.7894736842105263
              precision    recall  f1-score   support

           0       0.67      0.05      0.09        42
           1       0.80      0.96      0.87       806
           2       0.66      0.30      0.41       216

    accuracy                           0.79      1064
   macro avg       0.71      0.44      0.46      1064
weighted avg       0.77      0.79      0.75      1064

In [115]:
dfq = dfw.copy()

In [116]:
def label_quality(q):
    if q <= 4:
        return 0  # baja calidad
    elif q <= 6:
        return 1  # calidad media
    else:
        return 2  # buena calidad

dfw['quality_label'] = dfw['quality'].apply(label_quality)

In [117]:
# X = todas las columnas menos 'quality' y 'quality_label'
X = dfw.drop(columns=['quality', 'quality_label'])

# y = nuestra nueva variable objetivo
y = dfw['quality_label']

In [118]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [123]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [124]:
from sklearn.metrics import classification_report, accuracy_score

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7988721804511278
              precision    recall  f1-score   support

           0       0.33      0.05      0.08        42
           1       0.81      0.96      0.88       806
           2       0.71      0.36      0.47       216

    accuracy                           0.80      1064
   macro avg       0.62      0.45      0.48      1064
weighted avg       0.77      0.80      0.77      1064

fin